### PR TITLE
fix: add mutex for read/write to map of channels

### LINKED ISSUE #343: fix concurrent updates in version status
Sometimes the version status get updated concurrently on the watch version resolver, it cause the service to fail nad restart.

Check on `admin-api/adapter/gql/resolver.go` function `WatchVersion`.

```
2020-09-28T11:43:47.175906506Z 2020-09-28T11:43:47.175807989Z DEBUG [MonitoringService.WatchNodeStatus] waiting for stream.Recv()...                               │
│ 2020-09-28T11:43:47.347188779Z fatal error: concurrent map writes                                                                                                  │
│ 2020-09-28T11:43:47.350739776Z goroutine 499 [running]:                                                                                                            │
│ 2020-09-28T11:43:47.351236316Z runtime.throw(0x1013c3f, 0x15)                                                                                                      │
│ 2020-09-28T11:43:47.352025704Z     /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc00066f970 sp=0xc00066f940 pc=0x433592                                       │
│ 2020-09-28T11:43:47.352978914Z runtime.mapassign_faststr(0xeccca0, 0xc0005cfa40, 0xc0002ca420, 0x24, 0xc0002ca420)                                                 │
│ 2020-09-28T11:43:47.353667701Z     /usr/local/go/src/runtime/map_faststr.go:211 +0x3f7 fp=0xc00066f9d8 sp=0xc00066f970 pc=0x413307                                 │
│ 2020-09-28T11:43:47.35427183Z  github.com/konstellation-io/kre/admin/admin-api/adapter/gql.(*subscriptionResolver).WatchVersion(0xc0000862f8, 0x1235fc0, 0xc00014d │
│ 2020-09-28T11:43:47.354893671Z     /app/adapter/gql/resolver.go:438 +0x191 fp=0xc00066fa88 sp=0xc00066f9d8 pc=0xdae081
 ```

### PR DESCRIPTION
**Pull request by guumaster**
used for notifications to avoids service restart on concurrent access to it. Closes #343

### CODE REVIEW

File: admin/admin-api/adapter/gql/resolver.go [hunk 1]
```diff
@@ -6,16 +6,16 @@ import (
...
 
-	"github.com/konstellation-io/kre/admin/admin-api/adapter/config"
-
+	"github.com/go-playground/validator/v10"
 	"github.com/google/uuid"
+	"github.com/vektah/gqlparser/v2/gqlerror"
 
+	"github.com/konstellation-io/kre/admin/admin-api/adapter/config"
 	"github.com/konstellation-io/kre/admin/admin-api/adapter/dataloader"
 	"github.com/konstellation-io/kre/admin/admin-api/delivery/http/middleware"
```
Comment (guumaster) [inline admin/admin-api/adapter/gql/resolver.go:20]: changes before this line is just for sorting imports

**Review by angelsanchez — APPROVED** [review]
